import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f9f9f9",
        "outline-variant": "#c4c7c7",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#7afbb1",
        "surface-container": "#eeeeee",
        "surface-dim": "#dadada",
        tertiary: "#000000",
        "surface-container-high": "#e8e8e8",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed-dim": "#5cde97",
        "on-tertiary-fixed": "#002110",
        "on-secondary-container": "#fffbff",
        "on-secondary-fixed": "#410002",
        "secondary-fixed": "#ffdad6",
        outline: "#747878",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        "on-secondary-fixed-variant": "#93000d",
        "on-surface": "#1a1c1c",
        "on-tertiary-container": "#00975b",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-low": "#f3f3f3",
        "tertiary-container": "#002110",
        "on-tertiary-fixed-variant": "#00522f",
        "secondary-fixed-dim": "#ffb4ab",
        primary: "#000000",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c8c6c5",
        surface: "#f9f9f9",
        "secondary-container": "#e41f25",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f3131",
        "on-error": "#ffffff",
        "surface-tint": "#5f5e5e",
        "primary-fixed": "#e5e2e1",
        "primary-container": "#1c1b1b",
        "on-tertiary": "#ffffff",
        secondary: "#bb0014",
        "on-surface-variant": "#444748",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "section-padding": "80px",
        gutter: "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["var(--font-work-sans)", "Work Sans", "sans-serif"],
        h2: ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-work-sans)", "Work Sans", "sans-serif"],
        h3: ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        h1: ["var(--font-inter)", "Inter", "sans-serif"],
        inter: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["36px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
